title: Tohid Yousefi - Blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tohid Yousefi # add your name
author-img: tohid-yousefi.jpg # add your photo
about-author: My name is Tohid Yousefi and I am studying computer engineering (Ph.D.) at Dokuz Eylül University in Turkey. My field of work is mostly meta-heuristic algorithms. I am also very interested in machine learning algorithms, Python and MATLAB programming languages, and data science. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: tohid-yousefi # add your Github handle
social-linkedin: tohid-yousefi # add your Linkedin handle
social-email: tohid.yousefi@hotmail.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
